# send-to:
# + everyone
# + me
# + permission:<permission>
# + op
# + world:<world>
register-commands:
  - "rules"
  - "help"
commands:
  rules:
    permission: commands.rules
    send-to: everyone
    text:
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
  help:
    permission: commands.help
    send-to: me
    text:
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""